openapi: 3.0.3
info:
  title: Talen Score Project API
  version: 0.0.0
paths:
  /api/answer-list:
    get:
      operationId: answer_list_list
      tags:
      - answer-list
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Answer'
          description: ''
  /api/answer-list/{slug}/{id}/:
    get:
      operationId: answer_list_list_2
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      - in: path
        name: slug
        schema:
          type: string
        required: true
      tags:
      - answer-list
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Answer'
          description: ''
  /api/question-list:
    get:
      operationId: question_list_list
      tags:
      - question-list
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Question'
          description: ''
  /api/question-list/{slug}/:
    get:
      operationId: question_list_list_2
      parameters:
      - in: path
        name: slug
        schema:
          type: string
        required: true
      tags:
      - question-list
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Question'
          description: ''
  /api/question-list/{slug}/{id}/:
    get:
      operationId: question_list_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      - in: path
        name: slug
        schema:
          type: string
        required: true
      tags:
      - question-list
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Answer'
          description: ''
  /api/question-list/{slug}/options/{previous_answer}/:
    get:
      operationId: question_list_options_list
      parameters:
      - in: path
        name: previous_answer
        schema:
          type: integer
        required: true
      - in: path
        name: slug
        schema:
          type: string
        required: true
      tags:
      - question-list
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Answer'
          description: ''
components:
  schemas:
    Answer:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        question:
          type: integer
        answer:
          type: string
          nullable: true
          maxLength: 255
        previous_answer:
          type: integer
          nullable: true
        slug:
          type: string
          nullable: true
          maxLength: 50
          pattern: ^[-a-zA-Z0-9_]+$
      required:
      - id
      - question
    Question:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        question:
          type: string
          maxLength: 155
        slug:
          type: string
          nullable: true
          maxLength: 50
          pattern: ^[-a-zA-Z0-9_]+$
        answers:
          type: string
          readOnly: true
        question_depends_answer:
          type: array
          items:
            type: integer
      required:
      - answers
      - id
      - question
      - question_depends_answer
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
