# Generated by Django 4.2.2 on 2023-06-09 07:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("talentscoreAPI", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="answers",
            name="answer_text",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
