# Generated by Django 4.2.2 on 2023-06-09 07:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("talentscoreAPI", "0002_answers_answer_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answers",
            name="answer_text",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="answers",
            name="answers_option",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
