# Generated by Django 4.2.2 on 2023-06-12 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("talentscoreAPI", "0002_questions_question_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="answers",
            name="previous_answer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="talentscoreAPI.answers",
            ),
        ),
    ]
