# Generated by Django 4.2.2 on 2023-06-14 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("talentscoreAPI", "0002_rename_answer_text_answers_answer_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionFlow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "previous_answer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="talentscoreAPI.answers",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="talentscoreAPI.questions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Question Flow",
                "verbose_name_plural": "Question Flows",
                "ordering": ["order"],
            },
        ),
    ]
