# Generated by Django 4.2.2 on 2023-06-14 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("talentscoreAPI", "0003_questionflow"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionflow",
            name="question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="talentscoreAPI.questions",
            ),
        ),
    ]
