# Generated by Django 4.2.2 on 2023-06-09 07:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("talentscoreAPI", "0003_alter_answers_answer_text_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="answers",
            name="answer",
        ),
        migrations.RemoveField(
            model_name="answers",
            name="answers_option",
        ),
    ]
