# Generated by Django 4.2.2 on 2023-06-14 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("talentscoreAPI", "0005_alter_questionflow_options_remove_questionflow_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="questions",
            name="answer_depends_question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="talentscoreAPI.answers",
            ),
        ),
        migrations.DeleteModel(
            name="QuestionFlow",
        ),
    ]
