# Generated by Django 4.2.2 on 2023-06-13 07:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("talentscoreAPI", "0005_alter_questions_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questions",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
