# Generated by Django 4.2.2 on 2023-06-13 12:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("talentscoreAPI", "0006_alter_questions_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="answers",
            name="option_field",
            field=models.ManyToManyField(
                related_name="option_field", to="talentscoreAPI.questions"
            ),
        ),
    ]
