# Generated by Django 4.2.2 on 2023-06-14 10:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("talentscoreAPI", "0006_questions_answer_depends_question_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="questions",
            old_name="answer_depends_question",
            new_name="question_depends_answer",
        ),
    ]
