# Generated by Django 4.2.2 on 2023-06-14 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "talentscoreAPI",
            "0007_rename_answer_depends_question_questions_question_depends_answer",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="questions",
            name="question_depends_answer",
        ),
        migrations.AddField(
            model_name="questions",
            name="question_depends_answer",
            field=models.ManyToManyField(to="talentscoreAPI.answers"),
        ),
    ]
