# Generated by Django 4.2.2 on 2023-06-15 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("talentscoreAPI", "0008_remove_questions_question_depends_answer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questions",
            name="question_depends_answer",
            field=models.ManyToManyField(
                blank=True, null=True, to="talentscoreAPI.answers"
            ),
        ),
    ]
