# Generated by Django 4.2.2 on 2023-06-20 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("talentscoreAPI", "0009_alter_questions_question_depends_answer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answers",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="talentscoreAPI.questions",
            ),
        ),
        migrations.AlterField(
            model_name="questions",
            name="substage",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="talentscoreAPI.substage",
            ),
        ),
        migrations.AlterField(
            model_name="substage",
            name="stage",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="substage",
                to="talentscoreAPI.form",
            ),
        ),
    ]
